[project]
name = "titanic_data_analysis"
version = "0.1.0"
authors = [
    {name = "Hyo-Seung Ahn" , email = "lega2000@naver.com"}
] 
description = "타이타닉 데이터셋 분석 과제"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.10"
